### ISSUE TITLE
FX: SET ARPEGGIO is wrong

### ISSUE THREAD

**Issue by JO3RI** [TEAMarg/trackerEditor#2]
Arpeggio has to follow option that can be set:
- 2nd note = range from 0-16 (here as example 4)
- 3th note = range from 0-16 (here as example 3)
- only use second note ON (radio button)
- set retriggering ON (radio button)
- amount of ticks between notes = range from 0- 63

This will translate in:
0x47, 0x43, 0x80 + 0x40 + 20,	// FX: ARPEGGIO ON: notes =  +4 +3 / don't play third note = OFF / retrigger = OFF / ticks = 20

0x47 is the FX command
0x43 is the second and third note (left part of the byte and right part of the byte)
0x80 means only use the second note
0x40 means retrig 
20 means use 20 ticks between each note

**Comment by JO3RI** [comment]
![schermafbeelding 2017-06-12 om 09 39 43](https://user-images.githubusercontent.com/1590039/27027105-6d11319e-4f60-11e7-87ce-eb96eba3e5f2.png)

**Comment by JO3RI** [comment]
example with retrig and 3rd note
![arpeggio1](https://user-images.githubusercontent.com/1590039/27170160-2fc44c78-51ad-11e7-90ad-601752c23f6a.png)

example with no retrig and no 3rd note
![arpeggio2](https://user-images.githubusercontent.com/1590039/27170432-264cb350-51ae-11e7-97c0-332ee2d24ea9.png)

**Comment by JoJordens** [comment]
added in 8144c580bda982f3448c285310e6797a99571b40

**Comment by JO3RI** [comment]
The parameters in the above images are wrong see issue https://github.com/TEAMarg/trackerEditor/issues/27
