### ISSUE TITLE
problem with Arpeggio: no comma after last value and wrong amount of bytes taken in account

### ISSUE THREAD

**Issue by JO3RI** [TEAMarg/trackerEditor#25]
There is no comma after the last value !
The total amount of bytes for this command is always  **3** !!!

![schermafbeelding 2017-06-30 om 10 40 07](https://user-images.githubusercontent.com/1590039/27727964-dc8ac07a-5d80-11e7-839c-36cfba8a3460.png)

**Comment by JoJordens** [comment]
fixed in 7c8cc3e5e8943749a6dea73c6c60e26355dd1a7d
