### ISSUE TITLE
add "play song" button

### ISSUE THREAD

**Issue by JO3RI** [TEAMarg/trackerEditor#4]
![schermafbeelding 2017-04-24 om 10 07 12](https://cloud.githubusercontent.com/assets/1590039/25329584/ab14d784-28dc-11e7-92bc-ebab291cc72a.png)

add an extra button next to the other buttons, that plays the complete song like if you would drop it on the ATMplayer.

**Comment by JoJordens** [comment]
Added in 63cf895a86feb228e09a17da8fbd68aff4900a8b
