### ISSUE TITLE
FX in the "song editor" should act and look like a button, not text

### ISSUE THREAD

**Issue by JO3RI** [TEAMarg/trackerEditor#8]
![schermafbeelding 2017-04-25 om 10 23 11](https://cloud.githubusercontent.com/assets/1590039/25376088/48bb035c-29a3-11e7-8273-20a120e99254.png)

The "FX" looks like text and not a button you click on, this makes it hard for the user to know you can click on those.

**Comment by JoJordens** [comment]
fixed in 848c767dd0fd0fc6b90f6c0d8fbfeb6acdc2aa7e
